version: "2"

linters:
  default: none
  enable:
    - asciicheck
    - dogsled
    - errcheck
    - gomodguard
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unused
    - whitespace

  settings:
    dupl:
      threshold: 100

    lll:
      line-length: 950

    exhaustive:
      default-signifies-exhaustive: false

    funlen:
      lines: 100
      statements: 50

    goconst:
      min-len: 2
      min-occurrences: 2

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
